### ISSUE TITLE
Ubuntu and MacOS create files of different sizes in `make_frames` test

### ISSUE THREAD

**Issue by mhpob** [ocean-tracking-network/glatos#209]
Following a R CMD check on GitHub Actions, the test frame for make_frames is [189413 bytes on Ubuntu](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677120018#step:6:2672) and [226246 bytes on MacOS](https://github.com/ocean-tracking-network/glatos/actions/runs/7590506986/job/20677119585#step:6:2668). It is the expected ~30k bytes on Windows and the [developer's local Linux](https://github.com/ocean-tracking-network/glatos/pull/204#issuecomment-1904517945) so doesn't fail the test.

**Comment by mhpob** [comment]
See discussion from https://github.com/ocean-tracking-network/glatos/pull/204#issuecomment-1904500529 onward.

**Comment by mhpob** [comment]
@haydento  This looks to be an issue with the PNG driver, at least in part, here: https://github.com/ocean-tracking-network/glatos/blob/dev/R/vis-make_frames.r#L473-L477

Adding a `type=` arg to that chunk on my Windows machine:
`png(..., type = 'windows')` = 30919 bytes
`png(..., type = 'cairo')` = 187813 bytes
`png(..., type = 'cairo-png')` = 187831 bytes

Explicit reference to the type arg was added in https://github.com/ocean-tracking-network/glatos/commit/3ba79b7b73d82f3ac9cf930dac200499622516dd#diff-44d0b243d196f3dc4cae5405333fe9e86a2193c1c4fb6de2ea95c97983726041R418 then removed in https://github.com/ocean-tracking-network/glatos/commit/122d1455906d9f118c64b902bb2b94c4386f7949

From `?png`: 

> For the png device, type = "cairo" does the PNG output in the driver and so is compatible with the "windows" type. type = "cairo-png" uses cairographics' PNG backend which will never use a palette and normally creates a larger 32-bit ARGB file—this may work better for specialist uses with semi-transparent colours.

Still no idea why MacOS is double that, even. Maybe X11 or Quartz? Again from `?png`

> ## Differences between OSes
> These functions are interfaces to three or more different underlying devices.
>     - On Windows, devices based on plotting to a hidden screen using Windows' GDI calls.
>     - On platforms with support for X11, plotting to a hidden X11 display.
>     - On macOS when working at the console and when R is compiled with suitable support, using Apple's Quartz plotting system.
>     - Where support has been compiled in for cairographics, plotting on cairo surfaces. This may use the native platform support for fonts, or it may use fontconfig to support a wide range of font formats.
>     - Inevitably there will be differences between the options supported and output produced. Perhaps the most important are support for antialiased fonts and semi-transparent colours: the best results are likely to be obtained with the cairo- or Quartz-based devices where available.

**Comment by chrisholbrook** [comment]
The make_frames tests have always been tedious because the expectation file size changes frequently (presumably based on software updates) even on the same OS. In the short term, I'm keen to open this test up to only check that png is written with min. file size (not empty). @haydento @jdpye @mhpob Seem reasonable for now?

**Comment by haydento** [comment]
Sounds great to me.
________________________________
From: chrisholbrook ***@***.***>
Sent: Tuesday, January 23, 2024 12:12
To: ocean-tracking-network/glatos ***@***.***>
Cc: Hayden, Todd A ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ocean-tracking-network/glatos] Ubuntu and MacOS create files of different sizes in `make_frames` test (Issue #209)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



The make_frames tests have always been tedious because the expectation file size changes frequently (presumably based on software updates) even on the same OS. In the short term, I'm keen to open this test up to only check that png is written with min. file size (not empty). @haydento<https://github.com/haydento> @jdpye<https://github.com/jdpye> @mhpob<https://github.com/mhpob> Seem reasonable for now?

**Comment by mhpob** [comment]
@chrisholbrook @haydento is this something I should pull into #204 or would you like to patch separately?

**Comment by chrisholbrook** [comment]
@mhpob Feel free to pull into #204. thanks!

**Comment by mhpob** [comment]
Closed by #204 in https://github.com/ocean-tracking-network/glatos/pull/204/commits/e34860d1f9bf039c9a9747c6c35109fde678c43b
